/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xerial_jnuma_NumaNative */

#ifndef _Included_xerial_jnuma_NumaNative
#define _Included_xerial_jnuma_NumaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xerial_jnuma_NumaNative
 * Method:    allocLocal
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_xerial_jnuma_NumaNative_allocLocal
  (JNIEnv *, jobject, jint);

/*
 * Class:     xerial_jnuma_NumaNative
 * Method:    allocOnNode
 * Signature: (II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_xerial_jnuma_NumaNative_allocOnNode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     xerial_jnuma_NumaNative
 * Method:    free
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_xerial_jnuma_NumaNative_free
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
