/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xerial_jnuma_NumaNative */

#ifndef _Included_xerial_jnuma_NumaNative
#define _Included_xerial_jnuma_NumaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xerial_jnuma_NumaNative
 * Method:    numaAlloc
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_xerial_jnuma_NumaNative_numaAlloc
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
